### ISSUE TITLE
current state of the repository --> doesn't compile.

### ISSUE THREAD

**Issue by AdmiralSnyder** [Microsoft/VSLua#29]
hi, is this the correct current repository for the vslua project? it seems that lots of merging didn't complete preventing the cloned repository from compiling.
before i sink in too much time trying to get this to work, i thought i better ask.
examples: duplicated file "SyntaxKind", missing public property "Kind" on SyntaxNode etc. etc.

or has lua support in visual studio been abandoned (like, no commit in the last year)?

i think enabling as many things as possible in full VS still is a good idea and since i had to do some lua i wanted to do it in VS.

**Comment by AdmiralSnyder** [comment]
the issue with missing properties was a missing custom tool entry MSBuild:GenerateCodeFromAttributes on some files. maybe those were lost when the project was migratedfrom project.json to .csproj

**Comment by AdmiralSnyder** [comment]
how does this method get generated?
await this.DebuggerProperties.GetLuaDebuggerPropertiesAsync();
it is used in LuaDebugger.cs, but i cannot find the declaration anywhere.

**Comment by AArnott** [comment]
Those are generated by a code generator that runs with the build. I'll take a look to see what the problem is.

**Comment by AArnott** [comment]
Well, the build isn't broken -- as [attested to by appveyor](https://ci.appveyor.com/project/AArnott/vslua-2w2wn) which I just queued a fresh build on and it succeeds.
But I'll continue to investigate to see if something has degraded in the IDE experience.

**Comment by AArnott** [comment]
> when the project was migratedfrom project.json to .csproj

I don't think that ever happened. Why do you say it did? I see project.json files in this solution still. And that in fact may be your problem, if you're using VS 2017. It looks like this vslua.sln is likely to only work well in VS 2015.

**Comment by AdmiralSnyder** [comment]
so should we try to make it work in vs2017?
